#!/bin/bash

logline=`git log -1 --pretty=oneline`

cdir=$(readlink -f $(pwd))
host=$(/bin/hostname)
remotes=$(git remote -v |sed 's/(.*$//' |sort |uniq)

${HOME}/bin/_jot -t host\:$host -t headless -t git-commit -m "Committed:
$logline

in GIT_WORKING_DIR=$cdir
with remotes:
$remotes" --headless
