[package]
name = "jotlog"
version = "0.1.0"
authors = ["Joe Ardent <code@ardent.nebcorp.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2"
config = { version = "*", default-features = false, features = ["toml"] }
confy = "*"
diesel_migrations = "*"
diesel = { version = "1", features = ["sqlite"] }
lazy_static = "*"
mime = "0.3.13"
regex = "1"
serde = { version = "1", features = ["derive"] }
sublime_fuzzy = "*"
time = "0.1.40"
tui = "0.3"
uuid = { version = "*", default-features = false, features = ["v5", "v4"] }