#!/usr/bin/env python3

import sys, os, time
from pathlib import Path

START = '%%START%%'
END = '%%END%%'

TAGS = '%%TAGS%%'

LOGFILE = Path().home() / ".kaptanslawg"

def main():
    print("Hit ^d to end input")
    text = sys.stdin.read()
    date = time.strftime('%Y-%m-%d-%H:%M:%S')
    print
    print("enter comma-separated tags, enter when")
    tags = sys.stdin.readline().strip()

    ent = "\n".join([START, date, "\n", text, "%s %s" % (TAGS, tags), END, "\n"])

    with open(LOGFILE, 'a') as f:
        f.write(ent)

    return

if __name__ == "__main__":
    main()
    exit(0)
